language: java
jdk:
  - openjdk17
install:
  - mvn install -DskipTests
script:
  - mvn test
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: [nombre de tu aplicación en Heroku]
  on:
    branch: main
